#!/usr/bin/env bash

# utils__contains takes following arguments:
# $1     -- elem
# ${@:2} -- options
# and returns where one of the `options` equals the `elem`
function utils__contains() {
    local elem
    for elem in "${@:2}"; do
        [[ "$elem" == "$1" ]] && return 0
    done
    return 1
}

# utils__is_true takes single argument and
# returns 0 if argument equals "true" (case-insensitive)
# returns 1 otherwise
function utils__is_true() {
    bool="$(echo "$1" | tr '[:upper:]' '[:lower:]' | utils__str_strip)"
    if [ "$bool" == "true" ]; then
        return 0
    fi
    return 1
}


# utils__str_strip takes input from stdin and strips space characters
function utils__str_strip() {
    cat | tr -d '[:space:]'
}
