#!/usr/bin/env bash

source $DTOOLS/lib/internal/logging

function traceback() {
    local frame=0
    while caller $frame; do
        ((frame++))
    done
}

function assert() {
    if [ $? -ne 0 ]; then
        log_error "assert failed"
        log_raw "Traceback:"
        traceback 1>&3
        exit 1
    fi
}
